### ISSUE TITLE
No module named options.train_options

### ISSUE THREAD

**Issue by nikhilpanchal48** [facebookresearch/FashionPlus#12]
On step 4 i got the following error #ImportError: No module named options.test_options
Traceback (most recent call last):
  File "./encode_clothing_features.py", line 8, in <module>
    from options.train_options import TrainOptions
ImportError: No module named `options.train_options`
               

  4.  Encode input images into latent codes:
    Change ROOT_DIR in script to FashionPlus' absolute path on your system.

cd preprocess
./encode_shape_texture_features.sh

`/Desktop/FashionPlus-master/preprocess$ ./encode_shape_texture_features.sh
++ NZ=8
++ OUTPUT_NC=18
++ MAX_MULT=8
++ DOWN_SAMPLE=7
++ BOTNK=1d
++ LAMBDA_KL=0.0001
++ DIVIDE_K=4
++ for ARGUMENT in "$@"
+++ echo CLASS=humanparsing
+++ cut -f1 -d=
++ KEY=CLASS
+++ echo CLASS=humanparsing
+++ cut -f2 -d=
++ VALUE=humanparsing
++ case "$KEY" in
++ CLASS=humanparsing
++ for ARGUMENT in "$@"
+++ echo LABEL_DIR=/home/monika/Desktop/FashionPlus-master//datasets/labels/
+++ cut -f1 -d=
++ KEY=LABEL_DIR
+++ echo LABEL_DIR=/home/monika/Desktop/FashionPlus-master//datasets/labels/
+++ cut -f2 -d=
++ VALUE=/home/monika/Desktop/FashionPlus-master//datasets/labels/
++ case "$KEY" in
++ LABEL_DIR=/home/monika/Desktop/FashionPlus-master//datasets/labels/
++ for ARGUMENT in "$@"
+++ echo SHAPE_GEN_PATH=/home/monika/Desktop/FashionPlus-master//checkpoint/
+++ cut -f1 -d=
++ KEY=SHAPE_GEN_PATH
+++ echo SHAPE_GEN_PATH=/home/monika/Desktop/FashionPlus-master//checkpoint/
+++ cut -f2 -d=
++ VALUE=/home/monika/Desktop/FashionPlus-master//checkpoint/
++ case "$KEY" in
++ SHAPE_GEN_PATH=/home/monika/Desktop/FashionPlus-master//checkpoint/
++ python ./encode_features.py --phase test --dataroot ./datasets/demo --label_dir /home/monika/Desktop/FashionPlus-master//datasets/labels/ --label_txt_path ./datasets/humanparsing/clothing_labels.txt --dataset_param_file ./datasets/humanparsing/garment_label_part_map.json --name humanparsing --share_decoder --share_encoder --separate_clothing_unrelated --nz 8 --checkpoints_dir /home/monika/Desktop/FashionPlus-master//checkpoint/ --output_nc 18 --use_dropout --lambda_kl 0.0001 --max_mult 8 --n_downsample_global 7 --bottleneck 1d --resize_or_crop pad_and_resize --loadSize 256 --batchSize 1 --divide_by_K 4
Traceback (most recent call last):
  File "./encode_features.py", line 17, in <module>
    from options.test_options import TestOptions
ImportError: No module named options.test_options
Traceback (most recent call last):
  File "./encode_clothing_features.py", line 8, in <module>
    from options.train_options import TrainOptions
ImportError: No module named `options.train_options`

**Comment by CN-cpu** [comment]
解决了吗，我也遇到了同样的问题
