### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'results/Lab/demo/test_shape_codes.p'

### ISSUE THREAD

**Issue by mhaboali** [facebookresearch/FashionPlus#9]
I followed those step mentioned in the ReadMe file and it worked properly as expected until I reached the 4th command to run this command inside ./preprocess directory `./encode_shape_texture_features.sh`

And here's the tail of the log where the error messages exist
`/home/h/FashionPlus/checkpoint/humanparsing/latest_Separate_encoder.pth not exists yet!
/home/h/FashionPlus/checkpoint/humanparsing/latest_Together_encoder.pth not exists yet!
/home/h/FashionPlus/checkpoint/humanparsing/latest_Decoder.pth not exists yet!
create web directory /home/h/FashionPlus/checkpoint/humanparsing/web...
/home/h/anaconda3/envs/fashion/lib/python3.6/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
/home/h/anaconda3/envs/fashion/lib/python3.6/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
/home/h/anaconda3/envs/fashion/lib/python3.6/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "./encode_features.py", line 84, in <module>
    with open(save_name, 'wb') as writefile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/Lab/demo/test_shape_codes.p'
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=32 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "./encode_clothing_features.py", line 18, in <module>
    opt = TrainOptions().parse()
  File "/home/h/FashionPlus/generation/options/base_options.py", line 122, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/home/h/anaconda3/envs/fashion/lib/python3.6/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:32`

And here are the configuration from the log:
`./encode_shape_texture_features.sh
++ NZ=8
++ OUTPUT_NC=18
++ MAX_MULT=8
++ DOWN_SAMPLE=7
++ BOTNK=1d
++ LAMBDA_KL=0.0001
++ DIVIDE_K=4
++ for ARGUMENT in "$@"
+++ echo CLASS=humanparsing
+++ cut -f1 -d=
++ KEY=CLASS
+++ cut -f2 -d=
+++ echo CLASS=humanparsing
++ VALUE=humanparsing
++ case "$KEY" in
++ CLASS=humanparsing
++ for ARGUMENT in "$@"
+++ echo LABEL_DIR=/home/h/FashionPlus/datasets/labels/
+++ cut -f1 -d=
++ KEY=LABEL_DIR
+++ echo LABEL_DIR=/home/h/FashionPlus/datasets/labels/
+++ cut -f2 -d=
++ VALUE=/home/h/FashionPlus/datasets/labels/
++ case "$KEY" in
++ LABEL_DIR=/home/h/FashionPlus/datasets/labels/
++ for ARGUMENT in "$@"
+++ echo SHAPE_GEN_PATH=/home/h/FashionPlus/checkpoint/
+++ cut -f1 -d=
++ KEY=SHAPE_GEN_PATH
+++ echo SHAPE_GEN_PATH=/home/h/FashionPlus/checkpoint/
+++ cut -f2 -d=
++ VALUE=/home/h/FashionPlus/checkpoint/
++ case "$KEY" in
++ SHAPE_GEN_PATH=/home/h/FashionPlus/checkpoint/
++ python ./encode_features.py --phase test --dataroot ./datasets/demo --label_dir /home/h/FashionPlus/datasets/labels/ --label_txt_path ./datasets/humanparsing/clothing_labels.txt --dataset_param_file ./datasets/humanparsing/garment_label_part_map.json --name humanparsing --share_decoder --share_encoder --separate_clothing_unrelated --nz 8 --checkpoints_dir /home/h/FashionPlus/checkpoint/ --output_nc 18 --use_dropout --lambda_kl 0.0001 --max_mult 8 --n_downsample_global 7 --bottleneck 1d --resize_or_crop pad_and_resize --loadSize 256 --batchSize 1 --divide_by_K 4
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
bottleneck: 1d
center_crop: False
checkpoints_dir: /home/h/FashionPlus/checkpoint/
cluster_path: features_clustered_010.npy
condition_idx: None
dataroot: ./datasets/demo
dataset_mode: aligned
dataset_param_file: ./datasets/humanparsing/garment_label_part_map.json
display_id: 1
display_port: 8097
display_server: http://localhost
display_winsize: 256
divide_by_K: 4
engine: None
export_onnx: None
fineSize: 256
gpu_ids: [0]
how_many: 50
init_type: xavier
input_nc: 3
isTrain: False
label_dir: /home/h/FashionPlus/datasets/labels/
label_txt_path: ./datasets/humanparsing/clothing_labels.txt
lambda_kl: 0.0001
loadSize: 256
load_feat_dir: ./results/
log_to_filename: /checkpoint/kimberlyhsiao/.visdom/
max_dataset_size: inf
max_mult: 8
model: bicycle_gan
nThreads: 4
n_blocks_global: 9
n_downsample_global: 7
n_samples: 5
name: humanparsing
ndf: 64
nef: 64
ngf: 64
nl: relu
no_flip: False
norm: instance
ntest: inf
nz: 8
onnx: None
output_nc: 18
phase: test
reference_idx: None
resize_or_crop: pad_and_resize
results_dir: ./results/
separate_clothing_unrelated: True
serial_batches: False
share_decoder: True
share_encoder: True
suffix: 
swap_piece: None
tf_log: False
upsample: basic
use_dropout: True
verbose: False
where_add: all
which_direction: AtoB
which_epoch: latest
which_model_netE: resnet_256
which_model_netG: unet_256
-------------- End ----------------
dataset [AlignedDataset] was created
#training images = 3
/home/h/FashionPlus/checkpoint/humanparsing/latest_Separate_encoder.pth not exists yet!
/home/h/FashionPlus/checkpoint/humanparsing/latest_Together_encoder.pth not exists yet!
/home/h/FashionPlus/checkpoint/humanparsing/latest_Decoder.pth not exists yet!
`

**Comment by wlhsiao** [comment]
Hi,
The folder result/Lab/demo should be created before running the script. Will update the repo soonish, but creating this folder should solve this error.

**Comment by mhaboali** [comment]
Thanks for your reply,
Where should I create those directories?

I've tried to create those folders in several places, but I got the same error.

**Comment by ayush9198gupta** [comment]
Hello All,

I have tried all the steps mentioned in the repo. and its working but when i am trying the command or applying the last step to check the results with images 

Command run :-
`(  ./scripts/edit_and_visualize_demo.sh 3.jpg shape_and_texture True 0 10 0.25) 
`

**After execution it gives me error** 

```
"Traceback (most recent call last):
  File "update_demo.py", line 596, in <module>
    piece_shape_feat_dict = pickle.load(readfile)
EOFError: Ran out of input
Traceback (most recent call last):
  File "process_face.py", line 124, in <module>
    assert(bbox is not None), 'Cannot find file %s in dictionary' % fname
AssertionError: Cannot find file final_3.jpg in dictionary"
```

Note : All though this my file in results/Lab/demo/test_shape_codes.p is already presented in mentioned path but its not updated with results.

Kindly suggest
Thanks in advance

**Comment by hanchaoyuan** [comment]
> Hello All,
> 
> I have tried all the steps mentioned in the repo. and its working but when i am trying the command or applying the last step to check the results with images
> 
> Command run :-
> `( ./scripts/edit_and_visualize_demo.sh 3.jpg shape_and_texture True 0 10 0.25) `
> 
> **After execution it gives me error**
> 
> ```
> "Traceback (most recent call last):
>   File "update_demo.py", line 596, in <module>
>     piece_shape_feat_dict = pickle.load(readfile)
> EOFError: Ran out of input
> Traceback (most recent call last):
>   File "process_face.py", line 124, in <module>
>     assert(bbox is not None), 'Cannot find file %s in dictionary' % fname
> AssertionError: Cannot find file final_3.jpg in dictionary"
> ```
> 
> Note : All though this my file in results/Lab/demo/test_shape_codes.p is already presented in mentioned path but its not updated with results.
> 
> Kindly suggest
> Thanks in advance

Hello, did you solve this problem, I meet a similar problem.
